//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tester.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IWalletSimulator")]
    public interface IWalletSimulator {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWalletSimulator/GetAllUsers", ReplyAction="http://tempuri.org/IWalletSimulator/GetAllUsersResponse")]
        KMA.APZRP2019.WalletSimulator.DBModels.User[] GetAllUsers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWalletSimulator/GetAllUsers", ReplyAction="http://tempuri.org/IWalletSimulator/GetAllUsersResponse")]
        System.Threading.Tasks.Task<KMA.APZRP2019.WalletSimulator.DBModels.User[]> GetAllUsersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWalletSimulator/AddUser", ReplyAction="http://tempuri.org/IWalletSimulator/AddUserResponse")]
        void AddUser(KMA.APZRP2019.WalletSimulator.DBModels.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWalletSimulator/AddUser", ReplyAction="http://tempuri.org/IWalletSimulator/AddUserResponse")]
        System.Threading.Tasks.Task AddUserAsync(KMA.APZRP2019.WalletSimulator.DBModels.User user);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWalletSimulatorChannel : Tester.ServiceReference1.IWalletSimulator, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WalletSimulatorClient : System.ServiceModel.ClientBase<Tester.ServiceReference1.IWalletSimulator>, Tester.ServiceReference1.IWalletSimulator {
        
        public WalletSimulatorClient() {
        }
        
        public WalletSimulatorClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WalletSimulatorClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WalletSimulatorClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WalletSimulatorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public KMA.APZRP2019.WalletSimulator.DBModels.User[] GetAllUsers() {
            return base.Channel.GetAllUsers();
        }
        
        public System.Threading.Tasks.Task<KMA.APZRP2019.WalletSimulator.DBModels.User[]> GetAllUsersAsync() {
            return base.Channel.GetAllUsersAsync();
        }
        
        public void AddUser(KMA.APZRP2019.WalletSimulator.DBModels.User user) {
            base.Channel.AddUser(user);
        }
        
        public System.Threading.Tasks.Task AddUserAsync(KMA.APZRP2019.WalletSimulator.DBModels.User user) {
            return base.Channel.AddUserAsync(user);
        }
    }
}
